Repository Workiva/ichnaie, pull requests merged in 2019-04, with the labels that each got.

#1 Initial Commit to OpenSource Repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  LICENSE
  Makefile
  NOTICE
  README.md
  aviary.yaml
  documentation/css/default.css
  documentation/css/highlight.css
  documentation/ichnaie.core.html
  documentation/index.html
  documentation/js/highlight.min.js
  documentation/js/jquery.min.js
  documentation/js/page_effects.js
  java-src/ichnaie/TracingContext.java
  project.clj
  src/ichnaie/core.clj
  test/ichnaie/tracing_test.clj
  workivabuild.Dockerfile
Labels: InfoSec Review Required, Merge Requirements Unmet

#2 EVA-984 Add CircleCI to ichnaie
  .circleci/clojars/profiles.clj
  .circleci/config.yml
  .circleci/scripts/update-tocs.sh
  .circleci/scripts/verify-dockerfile.sh
  .circleci/scripts/verify-docs.sh
  .circleci/scripts/verify-license-headers.sh
  .gitattributes
  .gitignore
  Makefile
  README.md
  documentation/clojure/css/default.css
  documentation/clojure/highlight/highlight.min.js
  documentation/clojure/highlight/solarized-light.css
  documentation/clojure/ichnaie.core.html
  documentation/clojure/index.html
  documentation/clojure/js/jquery.min.js
  documentation/clojure/js/page_effects.js
  documentation/css/highlight.css
  documentation/ichnaie.core.html
  documentation/index.html
  documentation/java/allclasses-frame.html
  documentation/java/allclasses-noframe.html
  documentation/java/constant-values.html
  documentation/java/deprecated-list.html
  documentation/java/help-doc.html
  documentation/java/ichnaie/TracingContext.html
  documentation/java/ichnaie/package-frame.html
  documentation/java/ichnaie/package-summary.html
  documentation/java/ichnaie/package-tree.html
  documentation/java/index-all.html
  documentation/java/index.html
  documentation/java/overview-tree.html
  documentation/java/package-list
  documentation/java/script.js
  documentation/java/stylesheet.css
  package.json
  project.clj
  src/ichnaie/core.clj
  test/ichnaie/tracing_test.clj
  workivabuild.Dockerfile
Labels: Merge Requirements Met, RM Ready, Security Review Required

#5 Bump dependency recide 1.0.0 -> 1.0.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#6 RM-48866 Release ichnaie v0.1.1
  project.clj
Labels: Merge Requirements Met, RM Ready

#7 Updating dependencies to latest and greatest and removing deprecated code
  documentation/clojure/ichnaie.core.html
  documentation/clojure/index.html
  project.clj
  src/ichnaie/core.clj
Labels: Merge Requirements Unmet

#9 RM-48870 Release ichnaie v0.1.2
  project.clj
Labels: Merge Requirements Met, RM Ready

#3 EVA-986 Add Github Pages documentation to ichnaie
  Gemfile
  Makefile
  README.md
  _config.yml
  assets/css/style.scss
Labels: Merge Requirements Met, RM Ready

#10 Add link to java docs as well
  README.md
Labels: Merge Requirements Met, RM Ready
